In [8]:
#匯入檔案(spotify kpop2021,2022最多收聽數藝人及團體)
import pandas as pd
data2021=pd.read_csv("2021.csv")
data2021

    排名      artist
0    1         BTS
1    2   BLACKPINK
2    3       TWICE
3    4  Stray Kids
4    5         TXT
5    6          IU
6    7   SEVENTEEN
7    8        ITZY
8    9         EXO
9   10  Red Velvet
10  11     ENHYPEN
11  12   NCT DREAM
12  13     NCT 127
13  14    (G)I-DLE
14  15       ATEEZ
15  16     MAMAMOO
16  17        Rosé
17  18        DAY6
18  19        Lisa
19  20     Agust D
20  21    MONSTA X
21  22        GOT7
22  23       LOONA
23  24     Taeyeon
24  25    Baekhyun
25  26      SHINee
26  27       aespa
27  28       NCT U
28  29      IZ*ONE
29  30    Jay Park

In [9]:
data2022=pd.read_csv("2022.csv")
data2022

    排名       artist
0    1          BTS
1    2    BLACKPINK
2    3        TWICE
3    4   Stray Kids
4    5    SEVENTEEN
5    6          TXT
6    7      ENHYPEN
7    8         ITZY
8    9     Jungkook
9   10     (G)I-DLE
10  11   Red Velvet
11  12        aespa
12  13         Lisa
13  14          IVE
14  15    NCT DREAM
15  16       J-Hope
16  17           IU
17  18        ATEEZ
18  19      NCT 127
19  20          EXO
20  21     TREASURE
21  22            V
22  23      Taeyeon
23  24  LE SSERAFIM
24  25     NewJeans
25  26        STAYC
26  27          PSY
27  28      BIGBANG
28  29     MONSTA X
29  30       Kep1er

In [11]:
#列出子集合s1
s1=set(data2021["artist"])
s1

{'(G)I-DLE',
 'ATEEZ',
 'Agust D',
 'BLACKPINK',
 'BTS',
 'Baekhyun',
 'DAY6',
 'ENHYPEN',
 'EXO',
 'GOT7',
 'ITZY',
 'IU',
 'IZ*ONE',
 'Jay Park',
 'LOONA',
 'Lisa',
 'MAMAMOO',
 'MONSTA X',
 'NCT 127',
 'NCT DREAM',
 'NCT U',
 'Red Velvet',
 'Rosé',
 'SEVENTEEN',
 'SHINee',
 'Stray Kids',
 'TWICE',
 'TXT',
 'Taeyeon',
 'aespa'}

In [12]:
#列出子集合s1
s2=set(data2022["artist"])
s2

{'(G)I-DLE',
 'ATEEZ',
 'BIGBANG',
 'BLACKPINK',
 'BTS',
 'ENHYPEN',
 'EXO',
 'ITZY',
 'IU',
 'IVE',
 'J-Hope',
 'Jungkook',
 'Kep1er',
 'LE SSERAFIM',
 'Lisa',
 'MONSTA X',
 'NCT 127',
 'NCT DREAM',
 'NewJeans',
 'PSY',
 'Red Velvet',
 'SEVENTEEN',
 'STAYC',
 'Stray Kids',
 'TREASURE',
 'TWICE',
 'TXT',
 'Taeyeon',
 'V',
 'aespa'}

In [28]:
#交集
#2021與2022皆有上榜的團體或歌手
s1&s2
print("2021與2022皆有上榜的團體或歌手數量:",len(s1&s2))
s1&s2

2021與2022皆有上榜的團體或歌手數量: 19
19

{'(G)I-DLE',
 'ATEEZ',
 'BLACKPINK',
 'BTS',
 'ENHYPEN',
 'EXO',
 'ITZY',
 'IU',
 'Lisa',
 'MONSTA X',
 'NCT 127',
 'NCT DREAM',
 'Red Velvet',
 'SEVENTEEN',
 'Stray Kids',
 'TWICE',
 'TXT',
 'Taeyeon',
 'aespa'}

In [29]:
#聯集
#2021或2022有上榜的團體或歌手
s1|s2
print("2021或2022有上榜的團體或歌手數量:",len(s1|s2))
s1|s2

2021與2022皆有上榜的團體或歌手數量: 41

{'(G)I-DLE',
 'ATEEZ',
 'Agust D',
 'BIGBANG',
 'BLACKPINK',
 'BTS',
 'Baekhyun',
 'DAY6',
 'ENHYPEN',
 'EXO',
 'GOT7',
 'ITZY',
 'IU',
 'IVE',
 'IZ*ONE',
 'J-Hope',
 'Jay Park',
 'Jungkook',
 'Kep1er',
 'LE SSERAFIM',
 'LOONA',
 'Lisa',
 'MAMAMOO',
 'MONSTA X',
 'NCT 127',
 'NCT DREAM',
 'NCT U',
 'NewJeans',
 'PSY',
 'Red Velvet',
 'Rosé',
 'SEVENTEEN',
 'SHINee',
 'STAYC',
 'Stray Kids',
 'TREASURE',
 'TWICE',
 'TXT',
 'Taeyeon',
 'V',
 'aespa'}

In [31]:
#差集2021
#2021有上榜但2022沒有上榜的團體或歌手
s1-(s1&s2)
print("2021有上榜但2022沒有上榜的團體或歌手:",len(s1-(s1&s2)))
s1-(s1&s2)

2021有上榜但2022沒有上榜的團體或歌手: 11

{'Agust D',
 'Baekhyun',
 'DAY6',
 'GOT7',
 'IZ*ONE',
 'Jay Park',
 'LOONA',
 'MAMAMOO',
 'NCT U',
 'Rosé',
 'SHINee'}

In [33]:
#差集2022
#2022有上榜但2021沒有上榜的團體或歌手
s2-(s1&s2)
print("2022有上榜但2021沒有上榜的團體或歌手:",len(s2-(s1&s2)))
s2-(s1&s2)

2022有上榜但2021沒有上榜的團體或歌手: 11

{'BIGBANG',
 'IVE',
 'J-Hope',
 'Jungkook',
 'Kep1er',
 'LE SSERAFIM',
 'NewJeans',
 'PSY',
 'STAYC',
 'TREASURE',
 'V'}

In [36]:
#對稱差集
#只有上榜2021或2022其中一年的團體或歌手
(s1|s2)-(s1&s2)
print("只有上榜2021或2022其中一年的團體或歌手",len((s1|s2)-(s1&s2)))
(s1|s2)-(s1&s2)

只有上榜2021或2022其中一年的團體或歌手 22

{'Agust D',
 'BIGBANG',
 'Baekhyun',
 'DAY6',
 'GOT7',
 'IVE',
 'IZ*ONE',
 'J-Hope',
 'Jay Park',
 'Jungkook',
 'Kep1er',
 'LE SSERAFIM',
 'LOONA',
 'MAMAMOO',
 'NCT U',
 'NewJeans',
 'PSY',
 'Rosé',
 'SHINee',
 'STAYC',
 'TREASURE',
 'V'}